
# SEO settings
title: "Just"
title2: "Blog" # default: ""
description: "One Small Step For a Man One Giant Leap for Mankind"
keywords: "architecture, engineering, software, swift, reactive, reactivecocoa, rxswift, mvvm, mvc, mvp"
url: http://leonov.co
baseurl: null

google_analytics: UA-1597634-9
repo: http://nikita-leonov/nikita-leonov.github.io
disqus_shortname: "leonovco"
twitter_username: "leonovco"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Nikita Leonov"
  job      : "Mobile Engineer"
  bio      : "1+1=3 is always TRUE in my world, a balance between binary and reality."
  thumb    : /images/author.jpg
  email    : me@leonov.co
  url      : http://leonov.co
  github   : http://github.com/nikita-leonov
  twitter  : http://twitter.com/leonovco
  facebook : https://www.facebook.com/nikita.leonov
  linkedin : https://www.linkedin.com/in/nikital

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@leonovco"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
